package com.phcworld.mock

import com.phcworld.user.domain.User
import com.phcworld.user.service.port.UserRepository
import java.util.concurrent.atomic.AtomicLong

class FakeUserRepository: UserRepository {

    private val autoGeneratedId = AtomicLong(0)
    private val data: MutableList<User> = ArrayList<User>()

    override fun registerUser(user: User): User {
        if (user.id == null || user.id!! == 0L) {
            val newUser: User = User(user.email, user.password, user.name, autoGeneratedId.incrementAndGet())
            data.add(newUser)
            return newUser
        } else {
            data.removeIf({ it.id == user.id })
            data.add(user)
            return user
        }
    }
}